---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-tomcat-blue
  labels:
    app: ml-tomcat-blue
    owner: maplelabs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-tomcat-blue
      owner: maplelabs
  template:
    metadata:
      labels:
        app: ml-tomcat-blue
        owner: maplelabs
    spec:
      containers:
      - name: ml-tomcat-blue
        image: ravikumarp/ml-tomcat:blue
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: kube-secret
