---
apiVersion: v1
kind: Service
metadata:
  name: ml-tomcat-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: 10Mbps
spec:
  selector:
    app: ml-tomcat
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-tomcat
  labels:
    app: ml-tomcat
    owner: maplelabs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-tomcat
      owner: maplelabs
  template:
    metadata:
      labels:
        app: ml-tomcat
        owner: maplelabs
    spec:
      containers:
      - name: ml-tomcat
        image: ravikumarp/ml-tomcat:blue
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: kube-secret
