---
  apiVersion: v1
  kind: Service
  metadata:
    name: ml-tomcat-service
    annotations:
      service.beta.kubernetes.io/oci-load-balancer-shape: 10Mbps
  spec:
    selector:
      app: ml-tomcat-green
      owner: maplelabs
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  